---
abstract: 'Map::Metro map for Barcelona'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Map-Metro-Plugin-Map-Barcelona
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
resources:
  bugtracker: https://github.com/Csson/p5-Map-Metro-Barcelona/issues
  homepage: https://github.com/Csson/p5-Map-Metro-Barcelona
  repository: https://github.com/Csson/p5-Map-Metro-Barcelona.git
version: '0.1000'
